name:                iscd-tg-model
version:             0.1.0.0
author:              "d86leader"
maintainer:          "d86leader@mail.com"
copyright:           "All rights reserved to d86leader"

dependencies:
- base >= 4.7 && < 5

executables:
  iscd-tg-model-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    dependencies:
    - monad-logger
    - network
    - persistent
    - persistent-sqlite
    - persistent-template
    - text
    - transformers
